name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2

    - name: Build with Gradle
      run: gradle build

    - name: Upload APK
      uses: actions/upload-artifact@v4  # 更新为 v4
      with:
        name: app-debug # 这个名字好型不能改，改成其它的会报错
        path: |
          app/build/outputs/apk/debug/app-debug.apk 
          app/build/outputs/apk/debug/output-metadata.json
        retention-days: 5